<?php

namespace ContainerSUb9AwR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateRssCommand_LazyService extends App_KernelDevContainer
{
    /*
     * Gets the private '.App\Command\GenerateRssCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\GenerateRssCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('generate-rss', [], 'Generate RSS feed from content source', false, #[\Closure(name: 'App\\Command\\GenerateRssCommand')] fn (): \App\Command\GenerateRssCommand => ($container->privates['App\\Command\\GenerateRssCommand'] ?? $container->load('getGenerateRssCommandService')));
    }
}
