<?php

namespace ContainerSUb9AwR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateRssCommandService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Command\GenerateRssCommand' shared autowired service.
     *
     * @return \App\Command\GenerateRssCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\GenerateRssCommand'] = $instance = new \App\Command\GenerateRssCommand(new \App\Service\JsonContentFetcher(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('string:default:content_source_default:CONTENT_SOURCE_URL')), new \App\Service\RssBuilder(($container->privates['twig'] ?? $container->load('getTwigService'))), new \App\Service\FileManager(($container->privates['filesystem'] ??= new \Symfony\Component\Filesystem\Filesystem()), (\dirname(__DIR__, 4).'/docs/')));

        $instance->setName('generate-rss');
        $instance->setDescription('Generate RSS feed from content source');

        return $instance;
    }
}
