<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSUb9AwR\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSUb9AwR/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerSUb9AwR.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerSUb9AwR\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerSUb9AwR\App_KernelDevContainer([
    'container.build_hash' => 'SUb9AwR',
    'container.build_id' => '5c252366',
    'container.build_time' => 1756314259,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSUb9AwR');
